class Translator:
    def __init__(self, initial_lang="en"):
        self.language = initial_lang
        self.translations = {
            "en": {
                "settings": "Settings",
                "history": "History",
                "start_dictation": "Start Dictation",
                "stop_dictation": "Stop Dictation",
                "dictation_toggle": "Dictation",
                "mic_device": "Recording Device",
                "sound_feedback": "Enable Sound Feedback",
                "ai_model": "AI Model Capacity",
                "nav_settings_desc": "Configure application behavior, microphone, and AI intelligence.",
                "nav_history_desc": "Review your previous transcriptions and copy them back.",
                "nav_vocabulary_desc": "Add custom words and jargon to improve recognition accuracy.",
                "nav_snippets_desc": "Define text expansions and auto-replacements for faster typing.",
                "model_desc": "Smaller = Faster. Larger = More accurate but slower.",
                "save_apply": "Save & Apply",
                "quit": "Quit",
                "transcription_history": "Transcription History",
                "welcome": "Welcome to ZenWhisper! Your transcriptions will appear here.",
                "copy": "Copy",
                "app_title": "Zen Settings",
                "history_title": "Zen History",
                "lang_select": "Interface Language",
                "sys_default": "System Default (Recommended)",
                "pulse_bridge": "PulseAudio Bridge",
                "download_error": "Download Error",
                "failed_download": "Failed to download model",
                "loading": "Loading model",
                "restart_required": "Language changed. Please restart the application for changes to take full effect.",
                "restart_now": "Restart Now",
                "restart_later": "Later",
                "autostart": "Launch at system startup",
                "mic_gain": "Microphone Sensitivity",
                "mic_gain_value": "Gain: {value}x",
                "hotkey_label": "Recording Hotkey",
                "hotkey_press": "Press keys...",
                "hotkey_current": "Current: {key}",
                "hub_title": "Zen Hub",
                "nav_settings": "Settings",
                "nav_history": "History",
                "nav_vocabulary": "Vocabulary",
                "nav_snippets": "Snippets",
                "vocabulary_title": "Custom Vocabulary",
                "snippets_title": "Text Snippets",
                "add_word": "Add Word",
                "add_snippet": "Add Snippet",
                "trigger": "Trigger Phrase",
                "expansion": "Expansion Text",
                "delete": "Delete",
                "thinking_notification": "Thinking... (recognizing)",
                "downloading": "Downloading AI Model...",
                "ready_to_apply": "Model ready. Click Save to apply.",
                "btn_download": "Download & Apply",
                "btn_save": "Save & Apply",
                "model_installed": "Model installed",
                "model_not_installed": "Model not installed"
            },
            "ru": {
                "settings": "Настройки",
                "history": "История",
                "start_dictation": "Начать диктовку",
                "stop_dictation": "Остановить диктовку",
                "dictation_toggle": "Запись",
                "mic_device": "Устройство записи",
                "sound_feedback": "Включить звуковой отклик",
                "ai_model": "Мощность ИИ",
                "nav_settings_desc": "Настройте поведение приложения, микрофон и интеллект системы.",
                "nav_history_desc": "История ваших записей с возможностью быстрого копирования.",
                "nav_vocabulary_desc": "Добавьте специфические слова для повышения точности распознавания.",
                "nav_snippets_desc": "Настройте автозамену текста для быстрого набора команд.",
                "model_desc": "Меньше = быстрее. Больше = точнее, но медленнее.",
                "save_apply": "Сохранить и применить",
                "quit": "Выход",
                "transcription_history": "История транскрипций",
                "welcome": "Добро пожаловать в ZenWhisper! Ваши тексты появятся здесь.",
                "copy": "Копировать",
                "app_title": "Настройки Zen",
                "history_title": "История Zen",
                "lang_select": "Язык интерфейса",
                "sys_default": "Системный (рекомендуется)",
                "pulse_bridge": "Мост PulseAudio",
                "download_error": "Ошибка загрузки",
                "failed_download": "Не удалось загрузить модель",
                "loading": "Загрузка модели",
                "restart_required": "Язык изменён. Пожалуйста, перезапустите приложение для полного применения.",
                "restart_now": "Перезапустить сейчас",
                "restart_later": "Позже",
                "autostart": "Запускать при старте системы",
                "mic_gain": "Чувствительность микрофона",
                "mic_gain_value": "Усиление: {value}x",
                "hotkey_label": "Горячая клавиша записи",
                "hotkey_press": "Нажмите клавиши...",
                "hotkey_current": "Текущая: {key}",
                "hub_title": "Zen Hub",
                "nav_settings": "Настройки",
                "nav_history": "История",
                "nav_vocabulary": "Словарь",
                "nav_snippets": "Сниппеты",
                "vocabulary_title": "Пользовательский словарь",
                "snippets_title": "Текстовые сниппеты",
                "add_word": "Добавить слово",
                "add_snippet": "Добавить сниппет",
                "trigger": "Фраза-триггер",
                "expansion": "Во что превратить",
                "delete": "Удалить",
                "thinking_notification": "Думаю... (распознавание)",
                "downloading": "Загрузка модели ИИ...",
                "ready_to_apply": "Модель загружена. Нажмите Сохранить.",
                "btn_download": "Скачать и применить",
                "btn_save": "Сохранить и применить",
                "model_installed": "Модель установлена",
                "model_not_installed": "Модель не установлена"
            }
        }

    def set_language(self, lang):
        if lang in self.translations:
            self.language = lang
            return True
        return False

    def get(self, key):
        return self.translations.get(self.language, self.translations["en"]).get(key, key)

# Global instance
translator = Translator()
